services:
  Drupal\Sniffs\Arrays\ArraySniff: ~
  Drupal\Sniffs\Arrays\DisallowLongArraySyntaxSniff: ~
  Drupal\Sniffs\CSS\ClassDefinitionNameSpacingSniff: ~
  Drupal\Sniffs\CSS\ColourDefinitionSniff: ~
  Drupal\Sniffs\Classes\ClassCreateInstanceSniff: ~
  Drupal\Sniffs\Classes\ClassDeclarationSniff: ~
  Drupal\Sniffs\Classes\FullyQualifiedNamespaceSniff: ~
  Drupal\Sniffs\Classes\InterfaceNameSniff: ~
  Drupal\Sniffs\Classes\PropertyDeclarationSniff: ~
  Drupal\Sniffs\Classes\UnusedUseStatementSniff: ~
  Drupal\Sniffs\Classes\UseLeadingBackslashSniff: ~
  Drupal\Sniffs\Commenting\ClassCommentSniff: ~
  Drupal\Sniffs\Commenting\DataTypeNamespaceSniff: ~
  Drupal\Sniffs\Commenting\DocCommentSniff: ~
  Drupal\Sniffs\Commenting\DocCommentAlignmentSniff: ~
  Drupal\Sniffs\Commenting\DocCommentStarSniff: ~
  Drupal\Sniffs\Commenting\FileCommentSniff: ~
  Drupal\Sniffs\Commenting\FunctionCommentSniff: ~
  Drupal\Sniffs\Commenting\HookCommentSniff: ~
  Drupal\Sniffs\Commenting\InlineCommentSniff: ~
  Drupal\Sniffs\Commenting\PostStatementCommentSniff: ~
  Drupal\Sniffs\Commenting\VariableCommentSniff: ~
  Drupal\Sniffs\ControlStructures\ControlSignatureSniff: ~
  Drupal\Sniffs\ControlStructures\ElseIfSniff: ~
  Drupal\Sniffs\ControlStructures\InlineControlStructureSniff: ~
  Drupal\Sniffs\Files\EndFileNewlineSniff: ~
  Drupal\Sniffs\Files\FileEncodingSniff: ~
  Drupal\Sniffs\Files\LineLengthSniff: ~
  Drupal\Sniffs\Files\TxtFileLineLengthSniff: ~
  Drupal\Sniffs\Formatting\MultiLineAssignmentSniff: ~
  Drupal\Sniffs\Formatting\MultipleStatementAlignmentSniff: ~
  Drupal\Sniffs\Formatting\SpaceInlineIfSniff: ~
  Drupal\Sniffs\Formatting\SpaceUnaryOperatorSniff: ~
  Drupal\Sniffs\Functions\DiscouragedFunctionsSniff: ~
  Drupal\Sniffs\Functions\FunctionDeclarationSniff: ~
  Drupal\Sniffs\InfoFiles\AutoAddedKeysSniff: ~
  Drupal\Sniffs\InfoFiles\ClassFilesSniff: ~
  Drupal\Sniffs\InfoFiles\DuplicateEntrySniff: ~
  Drupal\Sniffs\InfoFiles\RequiredSniff: ~
  Drupal\Sniffs\Methods\MethodDeclarationSniff: ~
  Drupal\Sniffs\NamingConventions\ValidClassNameSniff: ~
  Drupal\Sniffs\NamingConventions\ValidFunctionNameSniff: ~
  Drupal\Sniffs\NamingConventions\ValidGlobalSniff: ~
  Drupal\Sniffs\NamingConventions\ValidVariableNameSniff: ~
  Drupal\Sniffs\Scope\MethodScopeSniff: ~
  Drupal\Sniffs\Semantics\ConstantNameSniff: ~
  Drupal\Sniffs\Semantics\EmptyInstallSniff: ~
  Drupal\Sniffs\Semantics\FunctionAliasSniff: ~
  Drupal\Sniffs\Semantics\FunctionTSniff: ~
  Drupal\Sniffs\Semantics\FunctionWatchdogSniff: ~
  Drupal\Sniffs\Semantics\InstallHooksSniff: ~
  Drupal\Sniffs\Semantics\LStringTranslatableSniff: ~
  Drupal\Sniffs\Semantics\PregSecuritySniff: ~
  Drupal\Sniffs\Semantics\RemoteAddressSniff: ~
  Drupal\Sniffs\Semantics\TInHookMenuSniff: ~
  Drupal\Sniffs\Semantics\TInHookSchemaSniff: ~
  Drupal\Sniffs\Strings\UnnecessaryStringConcatSniff: ~
  Drupal\Sniffs\WhiteSpace\CloseBracketSpacingSniff: ~
  Drupal\Sniffs\WhiteSpace\CommaSniff: ~
  Drupal\Sniffs\WhiteSpace\EmptyLinesSniff: ~
  Drupal\Sniffs\WhiteSpace\NamespaceSniff: ~
  Drupal\Sniffs\WhiteSpace\ObjectOperatorIndentSniff: ~
  Drupal\Sniffs\WhiteSpace\ObjectOperatorSpacingSniff: ~
  Drupal\Sniffs\WhiteSpace\OpenBracketSpacingSniff: ~
  Drupal\Sniffs\WhiteSpace\OpenTagNewlineSniff: ~
  Drupal\Sniffs\WhiteSpace\OperatorSpacingSniff: ~
  Drupal\Sniffs\WhiteSpace\ScopeClosingBraceSniff: ~
  Drupal\Sniffs\WhiteSpace\ScopeIndentSniff: ~
